name: habits_plus
description: The Best Mobile Habit Tracker & Todo app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Firebase & Auth
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.1.1
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  flutter_twitter_login: "^1.1.0"

  # UI
  calendar_strip: ^1.0.4
  configurable_expansion_tile: ^1.0.0
  material_design_icons_flutter: ^4.0.5045
  eva_icons_flutter: ^1.0.4
  flutter_calendar: ^0.0.9
  cached_network_image: ^2.0.0
  photo_view: ^0.9.2
  flutter_zoom_drawer: ^1.0.1
  flutter_staggered_animations: ^0.1.2
  flare_flutter: ^2.0.3
  percent_indicator: ^2.1.1+1
  fl_chart: ^0.9.0

  # Other
  provider: ^4.0.2
  http: ^0.12.0+4
  date_util: ^0.1.4
  uuid: ^2.0.4
  async: ^2.4.0
  get_it: ^4.0.0
  collection: any
  flutter_local_notifications: ^1.4.1
  image_picker: ^0.6.4
  image_cropper: ^1.2.1
  shared_preferences: ^0.5.6+3
  logger: ^0.9.1
  path_provider: ^1.6.7
  flutter_image_compress: ^0.6.7
  device_info: ^0.4.2+3
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/logo.png"
  adaptive_icon_background: "assets/launcher/logo.png"
  adaptive_icon_foreground: "assets/launcher/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lang/
    - assets/flare/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAY-REGULAR.TTF
        - asset: assets/fonts/SFPRODISPLAY-LIGHT.TTF
          weight: 300
        - asset: assets/fonts/SFPRODISPLAY-MEDIUM.TTF
          weight: 600
    - family: custom_icons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
